### ISSUE TITLE
current channel not available 

### ISSUE THREAD

**Issue by ghost** [samuroi/SamuROI#32]
Hi,
I'm trying to install samuroi on my mac but whenever I attempt to install either the pyqt=4 or actual samuroi package I get this error message:

Last login: Sun Apr 12 11:38:49 on ttys000
(base) cex@CEXs-MacBook-Pro ~ % cd ./documents
(base) cex@CEXs-MacBook-Pro documents % conda install SamuROI-develop
Collecting package metadata (current_repodata.json): done
Solving environment: failed with initial frozen solve. Retrying with flexible solve.
Collecting package metadata (repodata.json): done
Solving environment: failed with initial frozen solve. Retrying with flexible solve.

PackagesNotFoundError: The following packages are not available from current channels:

  - samuroi-develop

Current channels:

  - https://repo.anaconda.com/pkgs/main/osx-64
  - https://repo.anaconda.com/pkgs/main/noarch
  - https://repo.anaconda.com/pkgs/r/osx-64
  - https://repo.anaconda.com/pkgs/r/noarch
  - https://conda.anaconda.org/conda-forge/osx-64
  - https://conda.anaconda.org/conda-forge/noarch

To search for alternate channels that may provide the conda package you're
looking for, navigate to

    https://anaconda.org

and use the search bar at the top of the page.

Are there additional channels that I need to install these packages?

Thanks for your help!

**Comment by martinitus** [comment]
Hi @lvm1995, samuroi is not available directly via the conda package manager, so
`conda install SamuROI-develop` will not work. Instead, you need to clone the source code and install it with conda develop mode as described in the readme. I haven't tested it with any recent conda version thou, and pyqt4 is also pretty outdated already :-(
