### ISSUE TITLE
problem with modifying rois imported from hdf5 files

### ISSUE THREAD

**Issue by fjohenning** [samuroi/SamuROI#7]
ROIS imported from hdf5 files cannot be further manipulated: opened a branch mask, the branch mask cannot be further moved in x, y, not possible to update the segments etc

**Comment by martinitus** [comment]
confirmed.
Because branch constructor does not set .x .y members  when created from raw data

**Comment by martinitus** [comment]
Please run `git pull origin master` and test again.

**Comment by fjohenning** [comment]
still getting the same error message after update:
AttributeError: 'numpy.ndarray' object has no attribute 'x'

**Comment by fjohenning** [comment]
and, with the error message, shifting does not work..
